### ISSUE TITLE
improve use of symlinks within the ScopeSim world 

### ISSUE THREAD

**Issue by JuHeart** [AstarVienna/irdb#101]
We noticed that the current use of symlinks in the path is not straight forwardly compatible with all operating systems. 

This is an example, breaking the use of the example notebooks on Windows, out of the box: https://github.com/AstarVienna/irdb/blob/dev_master/MICADO/docs/example_notebooks/inst_pkgs

Symlink functionality should be defined within the python code (as discussed via DM with @hugobuddel ) to improve inter-OS-operability

**Comment by hugobuddel** [comment]
So indeed, [git does not by default create correct symlinks](https://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows):

> This makes symlinks created and committed e.g. under Linux appear as plain text files that contain the link text under Windows

So in order to have a smooth experience with an IRDB git clone, a windows user would have had to do:

1. Turn on developer mode in windows to allow symlinks
2. Configure git to actually create the symlinks

Apparently the github runners are configured this way too. While I think it would still be useful for users to follow that, it would be better if things would also just work out-of-the box for everyone. So I've created https://github.com/AstarVienna/ScopeSim/pull/210 to work around the issue by determining wether a part of a path is actually a file that should have been a symlink.

Perhaps I went overboard with this a bit, but well, I wanted to learn how this actually works. There a many ways to improve the current situation, e.g. not requiring a symlink in the first place, but that will have to wait.

I'm not yet putting out a new version of ScopeSim with this change, because I want to get some other changes in first (primarily improvements that ensure that an upgrade of ScopeSim goes smoothly, because I don't to trade one problem for another).
