### ISSUE TITLE
Update TRACE files in MICADO_Sci

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/irdb#48]
The TRACE files in MICADO_Sci, e.g. `TRACE_SCI_3arcsec.fits` are in some old format that have `x0` and `x1` etc. and should be updated to the new format. (I don't know what that format is.)

#47 updates MICADO_Sci/MICADO_Sci_SPEC.yaml to say that x == x0 etc, which makes the test pass, but is not a proper solution.

**Comment by oczoske** [comment]
I don't understand the point of these files, the trace (there's only one) does not resemble the real ones at all. y values are from 166 mm to 1100 mm which is way off the detector array... I'd suggest xfailing the test until the idea behind this is made clear. 
In principle, a "science" trace should align with the detector columns, with wavelength a linear function of detector rows, with a mean dispersion similar to the actual traces. In the case of MICADO, I'm not sure whether the order structure should be preserved and how to deal with the detector gaps.

The new format has four columns `wavelength`, `xi` (or `s`), `x`, `y` (plus `r50` and `r80`), where for instance `x` is just the concatenation of `x0`, `x1`, ... `wavelength` has (or can have) repeating values. This is because we never know how many `x` columns we will get (we're given five for MICADO, but eleven for the METIS long-slit mode).

**Comment by hugobuddel** [comment]
Thanks for the explanation. I don't really know what these trace files actually contain or how they are represented. I believe @astronomyk  is waiting for new traces from Frank Grupp, so that would probably resolve this issue properly.

The best moment to mark these tests as `xfail` and create this issue would probably have been when the tests first broke. Now I was a bit fumbling around, trying to piece together what happened.

**Comment by teutoburg** [comment]
AFAIK, MICADO_Sci is no longer supported (in favor of just MICADO), so I'm closing this as irrelevant. If I'm mistaken, feel free to reopen and elaborate.

**Comment by hugobuddel** [comment]
Created #171 instead of reopening this, because we should remove MICADO_Sci if we don't fix it.
